### ISSUE TITLE
Create a Database Model

### ISSUE THREAD

**Issue by EyuEyu** [CSCI-GA-2820-SP24-003/promotions#3]
**As a** technique team
**I need** to create a  database
**So that** we could store promotions
   
 ### Details and Assumptions
 * Create a PostgreSQL database
 * Attributes include ID, DATE, NAME, PRODUCTS, RULE, DURATION, ETC
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that there is no database
 When we have a promotion
 Then we can add it to the database
```

**Comment by Anoushka21** [comment]
What all attributes should the db have? Promotion id, active (Boolean to signify if promotion is active), discount amount, discount percentage etc.?
Is each promotion customer specific or product specific?

**Comment by EyuEyu** [comment]
I don't think we could easily get access to the information about products for now. So, maybe we don't have to include it.
Besides, a promotion might not be a discount. It could also be "buy one get one". Therefore, maybe it's enough to store the promotion information as a string.
